{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms import validators


class LoginForm(Form):
    username = StringField(u'Username', validators=[validators.required()])
    password = PasswordField(u'Password', validators=[validators.optional()])

    def validate(self):
        from {{cookiecutter.app_name}}.models import User
        check_validate = super(LoginForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        # Does our the exist
        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append('Invalid username or password')
            return False

        # Do the passwords match
        if not user.check_password(self.password.data):
            self.username.errors.append('Invalid username or password')
            return False

        return True

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/__init__.py
#! ../env/bin/python
# -*- coding: utf-8 -*-

__author__ = '{{cookiecutter.full_name}}'
__email__ = '{{cookiecutter.email}}'
__version__ = '1.0'

from flask import Flask, g
try:
    from webassets.loaders import PythonLoader as PythonAssetsLoader
except ImportError:
    pass

from {{cookiecutter.app_name}}.controllers.main import main_controller
from {{cookiecutter.app_name}}.controllers.admin import admin_controller
from {{cookiecutter.app_name}}.controllers.file import file_controller

from {{cookiecutter.app_name}} import assets
from {{cookiecutter.app_name}}.models import db
from {{cookiecutter.app_name}}.controls import get_setting
from {{cookiecutter.app_name}}.decorators import import_user


from {{cookiecutter.app_name}}.extensions import (
    cache,
    assets_env,
    debug_toolbar,
    login_manager
)


def before_app_request():
    g.user = None
    g.upload_directory = get_setting('upload-directory', 'uploads/')
    g.allowed_extensions = get_setting('allowed-extensions', ['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'tiff'])
    g.max_file_size = get_setting('max-file-size', 16777216)  # 16 MB
    g.user = import_user()


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. {{cookiecutter.app_name}}.settings.ProdConfig

        env: The name of the current environment, e.g. prod or dev
    """

    app = Flask(__name__)

    app.config.from_object(object_name)

    if cache:
        # initialize the cache
        cache.init_app(app)

    if debug_toolbar:
        # initialize the debug tool bar
        debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    login_manager.init_app(app)

    # Import and register the different asset bundles
    if assets_env:
        assets_env.init_app(app)
        assets_loader = PythonAssetsLoader(assets)
        for name, bundle in assets_loader.load_bundles().items():
            assets_env.register(name, bundle)

    # register our blueprints
    main_controller.before_request(before_app_request)
    app.register_blueprint(main_controller)

    admin_controller.before_request(before_app_request)
    app.register_blueprint(admin_controller)

    file_controller.before_request(before_app_request)
    app.register_blueprint(file_controller)

    return app

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/controllers/admin.py
import os
import json

from datetime import datetime
from dateutil import parser

from flask import (Blueprint, render_template, flash, request, redirect,
                   jsonify, url_for, g)
from flask_login import login_user, logout_user, login_required

from {{cookiecutter.app_name}}.decorators import user_is, user_has
from {{cookiecutter.app_name}}.utils import failure, success
from {{cookiecutter.app_name}}.forms import LoginForm
from {{cookiecutter.app_name}}.models import File, Setting, Tag, User
from {{cookiecutter.app_name}}.controls import get_payload
from {{cookiecutter.app_name}}.mixin import safe_commit

try:
    from {{cookiecutter.app_name}}.extensions import cache
except ImportError:
    pass


admin_controller = Blueprint('admin_controller', __name__)


@admin_controller.route('/user_create', methods=['POST'])
@user_is('admin')
def create_user():
    return_value = success('The user was created.')
    payload = get_payload(request)

    user = User(username=payload.get('email'), password=payload.get('password'),
                name=payload.get('name'))

    valid = user.validate()

    if valid['success']:
        user.insert()
        safe_commit()
        return_value['id'] = user.id
    else:
        del(user)
        return_value = valid

    return jsonify(return_value)


@admin_controller.route('/user_retrieve', methods=['POST'])
@user_is('admin')
def retrieve_user():
    return_value = success('The user was retrieved.')
    payload = get_payload(request)
    user = User.get(payload.get('id'))

    if not user:
        return_value = failure('That user does not exist.')
    else:
        return_value['user'] = user.to_dict(camel_case=True)
        return_value['user'].pop('password')
        return_value['user'].pop('openid')

    return jsonify(return_value)


@admin_controller.route('/user_update', methods=['POST'])
@user_is('admin')
def update_user():
    return_value = success('The user was updated.')
    payload = get_payload(request)
    user = User.get(payload.get('id'))

    if not user:
        return_value = failure('That user does not exist.')
    else:
        if payload.get('password'):
            user.set_password(payload.get('password'))
        if payload.get('email'):
            user.email = payload.get('email')
        if payload.get('name'):
            user.name = payload.get('name')

        safe_commit()
        return_value['user'] = user.to_dict(camel_case=True)

    return jsonify(return_value)


@admin_controller.route('/admin/users/delete', methods=['POST'])
@user_is('admin')
def delete_user():
    return_value = success('The user was deleted.')
    payload = get_payload(request)

    if not g.user or g.user.id != payload.get('id'):
        user = User.filter(User.id == payload.get('id')).first()
        if user:
            user.active = False
            user.insert()
            safe_commit()
        else:
            return_value = failure('That user does not exist.')
    else:
        return_value = failure('You cannot delete the current user.')

    return jsonify(return_value)


@admin_controller.route('/admin/files', methods=['GET'])
@user_is('admin')
def admin_files_list():
    files = File.all()
    return render_template('files_list.html', files=files)


@admin_controller.route('/admin/files/add', methods=['GET'])
@user_is('admin')
def admin_files_add():
    return render_template('file.html')


@admin_controller.route('/admin/files/delete', methods=['POST'])
@user_is('admin')
def admin_files_delete():
    return_value = success('The file has been deleted.')
    payload = get_payload(request)
    afile = File.get(payload.get('id'))
    if afile:
        try:
            os.unlink(afile.path)
        except OSError:
            pass
        try:
            os.unlink(afile.thumbnail_path)
        except OSError:
            pass
        afile.delete()
        safe_commit()
    else:
        return_value = failure('File not found.')

    return jsonify(return_value)


@admin_controller.route('/admin/users', methods=['GET'])
@user_is('admin')
def admin_users_list():
    users = User.filter(User.active == True).all()
    return render_template('users_list.html', users=users, content_type="Pages")


@admin_controller.route('/admin/users/add', methods=['GET'])
@user_is('admin')
def admin_users_add():
    user = User()
    user.id = ''
    user.firstname = ''
    user.lastname = ''
    user.email = ''
    return render_template('user.html', user=user)


@admin_controller.route('/admin/users/edit/<string:user_id>', methods=['GET'])
@user_is('admin')
def admin_users_edit(user_id=''):
    user = User.get(user_id)
    return render_template('user.html', user=user)


@admin_controller.route('/admin/users/edit/post', methods=['POST'])
@user_is('admin')
def admin_users_edit_post():
    payload = get_payload(request)
    user_id = payload.get('user_id')
    if user_id:
        user = User.get(user_id)
        return_value = success('All profile values have been updated.')
    else:
        user = User()
        user.insert()
        return_value = success('User created.')
        if not payload.get('password'):
            return jsonify(failure('You must set a password for new users'))
        if not payload.get('email'):
            return jsonify(failure('You must set an email for new users'))
        if not payload.get('name'):
            return jsonify(failure('You must set a name for new users'))

    for key in payload:
        if key == 'password':
            user.set_password(payload[key])
        elif key != 'user_id':
            setattr(user, key, payload[key])

    g.user.insert()
    safe_commit()

    return jsonify(return_value)


@admin_controller.route('/admin/settings', methods=['GET'])
@user_is('admin')
def admin_settings():
    available_themes = [
        x.identifier for x in get_themes_list() if x.identifier != 'admin']
    settings = Setting.all()
    for setting in settings:
        if setting.name == 'blog-theme':
            setting.allowed = json.dumps(available_themes)
    return render_template('settings.html', settings=settings)


@admin_controller.route('/admin/content/delete', methods=['POST'])
@user_is('admin')
def admin_content_delete():
    return_value = success('The content has been deleted.')
    payload = get_payload(request)
    content = Content.get(payload.get('id'))
    if content:
        content.delete()
        safe_commit()
    else:
        return_value = failure('Content not found.')

    return jsonify(return_value)


@admin_controller.route('/admin/settings/post', methods=['POST'])
@user_is('admin')
def admin_settings_post():
    return_value = success('All settings have been updated.')
    payload = get_payload(request)

    for key in payload:
        setting = Setting.filter(Setting.name == key).first()
        setting.value = payload[key]
        setting.insert()

    safe_commit()

    return jsonify(return_value)


@admin_controller.route('/admin', methods=['GET'])
@admin_controller.route('/admin/', methods=['GET'])
@user_is('admin')
def admin():
    return render_template('index.html', user=g.user)

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/controllers/file.py
import os
import json

from flask import (Blueprint, flash, request, redirect, url_for,
                   send_from_directory, jsonify, g)
from flask_login import login_user, logout_user, login_required
from {{cookiecutter.app_name}}.decorators import user_is, user_has

from {{cookiecutter.app_name}}.utils import success
from {{cookiecutter.app_name}}.controls import get_payload
from {{cookiecutter.app_name}}.extensions import cache
from {{cookiecutter.app_name}}.models import File, Tag, User
from {{cookiecutter.app_name}}.mixin import safe_commit
from werkzeug.utils import secure_filename

file_controller = Blueprint('File_controller', __name__)

APP_ROOT = os.path.dirname(os.path.abspath(__file__))

def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1] in g.allowed_extensions


@file_controller.route('/upload_ajax', methods=['POST'])
def upload_ajax():
    return_value = success('The file was uploaded.')
    payload = get_payload(request)
    ufile = request.files['file']
    file_id = upload_file(payload, ufile)
    return_value['id'] = file_id
    return jsonify(return_value)


@file_controller.route('/upload', methods=['POST'])
def upload():
    payload = get_payload(request)
    ufile = request.files['file']
    file_id = upload_file(payload, ufile)
    if file_id:
        flash("File uploaded!")
    else:
        flash("There was a problem uploading that file.")
    return redirect("/admin/files/add")


def upload_file(payload, ufile):
    upload_folder = os.path.abspath(os.path.join(APP_ROOT, "../", '../', g.upload_directory))
    if ufile and allowed_file(ufile.filename):
        filename = secure_filename(ufile.filename)
        thumbnail_name = ''
        thumbnail_path = ''
        path = os.path.join(upload_folder, filename)
        print(path)
        if not os.path.isfile(path):
            ufile.save(path)
            try:
                # Create thumbnail
                from PIL import Image
                size = 128, 128
                im = Image.open(path)
                width, height = im.size
                im.thumbnail(size, Image.ANTIALIAS)
                file, ext = os.path.splitext(path)
                fname, fext = os.path.splitext(filename)
                ext = ext.lower()
                etype = ext.replace(".", "")
                if etype == 'jpg':
                    etype = 'jpeg'
                thumbnail_path = file + "_thumbnail" + ext
                thumbnail_name = fname + "_thumbnail" + ext
                im.save(thumbnail_path, etype)
            except (ImportError, IOError):
                width = 0
                height = 0

            afile = File(name=filename, path=path, thumbnail_name=thumbnail_name,
                         thumbnail_path=thumbnail_path, user_id=payload.get('user_id'),
                         size=os.path.getsize(path), width=width, height=height,
                         mimetype=ufile.mimetype)
            afile.insert()
            safe_commit()
            return afile.id
    return None


@file_controller.route('/uploads/<filename>')
def uploaded_file(filename):
    upload_folder = os.path.abspath(os.path.join(APP_ROOT, "../", '../', g.upload_directory))
    return send_from_directory(upload_folder, filename)


@file_controller.route('/get_tags', methods=['GET'])
# @cache.cached(timeout=CACHE_TIMEOUT)
def get_tags():
    tags = [t.name for t in Tag.all()]
    return json.dumps(tags)

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/controllers/main.py
from flask import (Blueprint, render_template, flash, request, redirect, url_for,
                   jsonify)
from flask_login import login_user, logout_user, login_required

from jinja2.exceptions import TemplateNotFound
from sqlalchemy import or_  # , and_

from {{cookiecutter.app_name}}.decorators import user_is, user_has, import_user
from {{cookiecutter.app_name}}.controls import get_payload, get_setting
from {{cookiecutter.app_name}}.utils import success, chunks
from {{cookiecutter.app_name}}.forms import LoginForm
from {{cookiecutter.app_name}}.models import Role, Setting, User
from {{cookiecutter.app_name}}.mixin import safe_commit, paginate, results_to_dict
try:
    from {{cookiecutter.app_name}}.extensions import cache
except ImportError:
    pass

main_controller = Blueprint('main_controller', __name__)


@main_controller.route('/')
# @cache.cached(timeout=1000)
def index():
    return render_template('index.html')


@main_controller.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()
        login_user(user)

        flash("Logged in successfully.", "success")
        return redirect(request.args.get("next") or url_for(".index"))

    return render_template("login.html", form=form)


@main_controller.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out.", "success")

    return redirect(url_for(".index"))


@main_controller.route("/restricted", methods=["GET", "POST"])
@login_required
@user_is('admin')
def restricted():
    return render_template("restricted.html")


@main_controller.route("/create_user")
@login_required
@user_has('create_users')
def create_user():
    return "You can only see this if you are logged in with 'create_users' permissions!", 200

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% assets "common_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {% endassets %}

        {% block css %}
        {% endblock %}

        <script type="text/javascript">
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove();
            });
        }, 4000);
        </script>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Site Title</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main_controller.index') }}">Home</a></li>

                    {% if not current_user.is_authenticated %}
                        <li><a href="{{ url_for('main_controller.login') }}">Login</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main_controller.logout') }}">Logout</a></li>
                    {% endif %}

                    <li><a href="{{ url_for('main_controller.restricted') }}">Restricted Page</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>

        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block body %}
            {% endblock %}
        </div>

        {% assets "common_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% block js %}
        {% endblock %}
    </body>
</html>

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/index.html
{%extends "base.html"%}

{%block title%}Home{% endblock %}

{%block body%}
    <div class="jumbotron">
        <h1>Site Title</h1>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h1>Welcome to Site Title. Please <a href="/login">Login</a>.</h1>
        </div>
    </div>

    <div class="row">
    </div>
{%endblock%}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/login.html
{%extends "base.html" %}

{%block title %}Login{% endblock %}

{%block body %}
    <h1 class="text-center">Site Title Login</h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form role="form" action="" method="post">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_="form-control") }}
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{%endblock %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/permission_denied.html
{%extends "base.html"%}

{%block title%}Restricted{% endblock %}

{%block body%}
    <div class="row">
        <div class="col-lg-12">
          <h1>Permission Denied</h1>
          <p>You do not have permission to access this page or perform this action.</p>
          <p><a href="javascript:history.back()">Go Back</a></p>
        </div>
    </div>

    <div class="row">
    </div>
{%endblock%}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/restricted.html
{%extends "base.html"%}

{%block title%}Restricted{% endblock %}

{%block body%}
    <div class="row">
        <div class="col-lg-12">
          <h1>Restricted Page</h1>
        </div>
    </div>

    <div class="row">
    </div>
{%endblock%}